---
apiVersion: v1
kind: Service
metadata:
  name: ssv-dkg-3-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-dkg-3
spec:
  type: ClusterIP
  ports:
    - port: 3030
      protocol: TCP
      targetPort: 3030
      name: port-3030
  selector:
    app: ssv-dkg-3
---
apiVersion: REPLACE_API_VERSION
kind: Deployment
metadata:
  labels:
    app: ssv-dkg-3
  name: ssv-dkg-3
  namespace: REPLACE_NAMESPACE
spec:
  replicas: REPLACE_REPLICAS
  selector:
    matchLabels:
      app: ssv-dkg-3
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ssv-dkg-3
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/role
                    operator: In
                    values:
                      - ssv-main
      containers:
      - name: ssv-dkg-3
        image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
        imagePullPolicy: Always
        resources:
          limits:
            cpu: REPLACE_NODES_CPU_LIMIT
            memory: REPLACE_NODES_MEM_LIMIT
        ports:
        - containerPort: 3030
        command: ["/bin/ssv-dkg", "start-operator", "--configPath=/data/config/config.yaml", "--privKeyPassword=/data/password", "--privKey=/data/encrypted_private_key_op3.json"]
        volumeMounts:
        - name: secrets-file
          mountPath: "/data/encrypted_private_key_op3.json"
          subPath: encrypted_private_key_op3.json
        - name: ssv-dkg-3-cm
          mountPath: /data/password
          subPath: password
        - name: ssv-dkg-3-cm
          mountPath: /data/config/config.yaml
          subPath: operator.yaml
      volumes:
        - name: secrets-file
          secret:
            secretName: ssv-dkg-3
        - name: ssv-dkg-3-cm
          configMap:
            name: ssv-dkg-3-cm
      tolerations:
        - effect: NoSchedule
          key: kubernetes.io/role
          operator: Exists
      hostNetwork: true
