privKey: /data/operator4/encrypted_private_key.json
privKeyPassword: /data/operator4/password
port: 3030
operatorID: 4
logLevel: info
logFormat: json
logLevelFormat: capitalColor
logFilePath: /data/operator4/output/operator4_logs_debug.log
outputPath: /data/operator4/output
