privKey: /data/operator6/encrypted_private_key.json
privKeyPassword: /data/operator6/password
port: 3030
operatorID: 66
logLevel: info
logFormat: json
logLevelFormat: capitalColor
logFilePath: /data/operator6/output/operator6_logs_debug.log
outputPath: /data/operator6/output
# serverTLSCertPath: /data/operator6/operator6.crt
# serverTLSKeyPath: /data/operator6/operator6.key