privKey: /data/operator5/encrypted_private_key.json
privKeyPassword: /data/operator5/password
port: 3030
operatorID: 5
logLevel: info
logFormat: json
logLevelFormat: capitalColor
logFilePath: /data/operator5/output/operator5_logs_debug.log
outputPath: /data/operator5/output
