privKey: /data/operator3/encrypted_private_key.json
privKeyPassword: /data/operator3/password
port: 3030
operatorID: 3
logLevel: info
logFormat: json
logLevelFormat: capitalColor
logFilePath: /data/operator3/output/operator3_logs_debug.log
outputPath: /data/operator3/output
