privKey: /data/operator1/encrypted_private_key.json
privKeyPassword: /data/operator1/password
port: 3030
operatorID: 1
logLevel: info
logFormat: json
logLevelFormat: capitalColor
logFilePath: /data/operator1/output/operator1_logs_debug.log
outputPath: /data/operator1/output
