operatorIDs: [1, 2, 3, 4]
newOperatorIDs: [5, 6, 7, 8]
oldID: "5518f05002fb4dfc808d220356996514769e4e9eaa8d6811"
owner: "0x81592c3de184a3e2c0dcb5a261bc107bfa91f494"
nonce: 0
network: "holesky"
outputPath: /data/initiator/output
logLevel: info
logFormat: json
logLevelFormat: capitalColor
logFilePath: /data/initiator/output/initiator_debug.log
